### docker-compose.override.yml (Development environment)
services:
  backend-api:   
    container_name: mmdddshop-backend-api
    image: luongtuananh/mmdddshop-backend-api
    build:
      context: .
      dockerfile: mmdddshop-backend/Dockerfile_backend    
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQLSERVER_HOST=${SQLSERVER_HOST}
      - SQLSERVER_HOST_PORT=${SQLSERVER_HOST_PORT}
      - SQLSERVER_DATABASE_NAME=${SQLSERVER_DATABASE_NAME}
      - SQLSERVER_USER=${SQLSERVER_USER}
      - SQLSERVER_PASSWORD=${SQLSERVER_PASSWORD}        
    ports:
      - "${API_HOST_PORT}:${API_DOCKER_CONTAINER_PORT}"    
    # volumes:
    #     - ./mmdddshop-backend/src/API/ModularMonolithDDD.API/logs:/app/logs       
    #     - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/home"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    depends_on:
      db-sqlserver:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - mmdddshop-network

  frontend-admin:  
    container_name: mmdddshop-frontend-admin  
    build:
        context: ./mmdddshop-frontend-admin
        dockerfile: Dockerfile_fe        
        args:
          ADMIN_DOCKER_CONTAINER_PORT: ${ADMIN_DOCKER_CONTAINER_PORT}
          VITE_API_URL: http://${API_HOST}:${API_HOST_PORT}/
          VITE_AUTHORITY: http://${API_HOST}:8082/realms/mmdddshop
          VITE_CLIENT_ID: admin-spa
          VITE_REDIRECT_URI: http://${ADMIN_HOST}:${ADMIN_HOST_PORT}/callback
    environment:
        - API_HOST_PORT=${API_HOST_PORT}
        - API_DOCKER_CONTAINER_PORT=${API_DOCKER_CONTAINER_PORT} 
        - ADMIN_HOST_PORT=${ADMIN_HOST_PORT}
        - ADMIN_DOCKER_CONTAINER_PORT=${ADMIN_DOCKER_CONTAINER_PORT} 
    ports:
        - "${ADMIN_HOST_PORT}:${ADMIN_DOCKER_CONTAINER_PORT}"    
    # volumes:
    #     - .mmdddshop-frontend-admin:/app
    #     - /app/node_modules            
    depends_on:
      backend-api:
       condition: service_healthy
    networks:
        - mmdddshop-network