### docker-compose.override.yml (BASE - common for all environments)
services:
  app-api:   
    build:
      context: .
      dockerfile: modular-monolith-ddd/Dockerfile      
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQLSERVER_HOST=${SQLSERVER_HOST}
      - SQLSERVER_HOST_PORT=${SQLSERVER_HOST_PORT}
      - SQLSERVER_DATABASE_NAME=${SQLSERVER_DATABASE_NAME}
      - SQLSERVER_USER=${SQLSERVER_USER}
      - SQLSERVER_PASSWORD=${SQLSERVER_PASSWORD}        
    ports:
      - "${API_HOST_PORT}:${API_PORT}"    
    volumes:
        - ./modular-monolith-ddd/src/API/ModularMonolithDDD.API/logs:/app/logs 
    depends_on:
      app-sqlserver:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    networks:
      - modular-monolith-network

  app-frontend:  
    build:
      context: ./modular-monolith-ddd-frontend-react
      dockerfile: Dockerfile.fe      
    environment:
      - API_HOST_PORT=${API_HOST_PORT}
      - API_PORT=${API_PORT} 
      - FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}      
    ports:
        - "${FRONTEND_HOST_PORT}:${FRONTEND_PORT}" 
    # volumes:
    #    - ./modular-monolith-ddd-frontend-react/src:/app/src
    #    - /app/node_modules            
    networks:
      - modular-monolith-network