### docker-compose.prod.yml
services:
  api:
    image: luongtuananh/modular-monolith-ddd-backend-api:prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SQLSERVER_HOST=database
      - SQLSERVER_HOST_PORT=1433
      - SQLSERVER_DATABASE_NAME=${SQLSERVER_DATABASE_NAME}
      - SQLSERVER_USER=${SQLSERVER_USER}
      - SQLSERVER_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "${API_HOST_PORT}:${API_PORT}"
    restart: always
    networks: 
      - modular-monolith-network
  
  frontend-admin: 
    image: luongtuananh/modular-monolith-ddd-frontend-admin:prod
    environment:
      - API_HOST_PORT=${API_HOST_PORT}
      - API_PORT=${API_PORT}
      - ADMIN_HOST_PORT=${ADMIN_HOST_PORT}  
    ports:
      - "${ADMIN_HOST_PORT}:${ADMIN_PORT}" 
    restart: always 
    networks: 
      - modular-monolith-network
  
  frontend-portal: 
    image: luongtuananh/modular-monolith-ddd-frontend-portal:prod
    environment:
      - API_HOST_PORT=${API_HOST_PORT}
      - API_PORT=${API_PORT}
      - PORTAL_HOST_PORT=${PORTAL_HOST_PORT}  
    ports:
      - "${PORTAL_HOST_PORT}:${PORTAL_PORT}" 
    restart: always 
    networks: 
      - modular-monolith-network
  
  database:
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "${SQLSERVER_HOST_PORT}:${SQLSERVER_PORT}"
    volumes:
      - vol_sqlserver_prod:/var/opt/mssql
      - ./modular-monolith-ddd/src/Database:/docker-entrypoint-initdb.d   
    restart: always
    networks: 
      - modular-monolith-network
  
  liquibase:
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:sqlserver://database:1433;databaseName=${SQLSERVER_DATABASE_NAME};encrypt=false
      - LIQUIBASE_COMMAND_USERNAME=${SQLSERVER_USER}
      - LIQUIBASE_COMMAND_PASSWORD=${SQLSERVER_PASSWORD}
    restart: "no"
    networks: 
      - modular-monolith-network

   # Keycloak for Production with Database
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # SQL Server Configuration
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://database:1433;databaseName=${SQLSERVER_DATABASE_NAME};encrypt=false;      
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "${IDENTITY_HOST_PORT}:${IDENTITY_PORT}"  
    command: start
    networks:
      - modular-monolith-network  

volumes:
  vol_sqlserver_prod: