# RUNTIME STAGE
# Creates user, set permissions, mount volumes, and expose ports
## Uses Microsoft's ASP.NET 9.0 image as the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

# Define Linux system user arguments for container security
# Creates non-root user to avoid running as root
ARG APP_USER=app_admin
ARG APP_GROUP=app_group
ARG APP_HOME=/app

# Creates non-root Linux system group, non-root Linux system user
RUN addgroup --system $APP_GROUP && \
    adduser --system --ingroup $APP_GROUP --home $APP_HOME $APP_USER && \
    mkdir -p $APP_HOME && \
    chown -R $APP_USER:$APP_GROUP $APP_HOME

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Switch to non-root user for application execution
USER $APP_USER

# BUILD STAGE
# Copies source + restores + builds
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /

# Copy solution and project files for dependency restoration
COPY ModularMonolithDDD.sln Directory.Packages.props Directory.Build.targets ./
COPY ["mmdddshop-backend/src/API/ModularMonolithDDD.API/ModularMonolithDDD.API.csproj", "mmdddshop-backend/src/API/ModularMonolithDDD.API/"]
COPY ["mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Domain/ModularMonolithDDD.BuildingBlocks.Domain.csproj", "mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Domain/"]
COPY ["mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Application/ModularMonolithDDD.BuildingBlocks.Application.csproj", "mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Application/"]
COPY ["mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Infrastructure/ModularMonolithDDD.BuildingBlocks.Infrastructure.csproj", "mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Infrastructure/"]
COPY ["mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Logging/ModularMonolithDDD.BuildingBlocks.Logging.csproj", "mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Logging/"]
COPY ["mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Domain/ModularMonolithDDD.Modules.UserAccess.Domain.csproj", "mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Domain/"]
COPY ["mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Application/ModularMonolithDDD.Modules.UserAccess.Application.csproj", "mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Application/"]
COPY ["mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Infrastructure/ModularMonolithDDD.Modules.UserAccess.Infrastructure.csproj", "mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Infrastructure/"]
COPY ["mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.IntegrationEvents/ModularMonolithDDD.Modules.UserAccess.IntegrationEvents.csproj", "mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.IntegrationEvents/"]

# Restore NuGet packages for each project (production only)
RUN dotnet restore mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Domain/ModularMonolithDDD.BuildingBlocks.Domain.csproj
RUN dotnet restore mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Application/ModularMonolithDDD.BuildingBlocks.Application.csproj
RUN dotnet restore mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Infrastructure/ModularMonolithDDD.BuildingBlocks.Infrastructure.csproj
RUN dotnet restore mmdddshop-backend/src/BuildingBlocks/ModularMonolithDDD.BuildingBlocks.Logging/ModularMonolithDDD.BuildingBlocks.Logging.csproj
RUN dotnet restore mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Domain/ModularMonolithDDD.Modules.UserAccess.Domain.csproj
RUN dotnet restore mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Application/ModularMonolithDDD.Modules.UserAccess.Application.csproj
RUN dotnet restore mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.Infrastructure/ModularMonolithDDD.Modules.UserAccess.Infrastructure.csproj
RUN dotnet restore mmdddshop-backend/src/Modules/UserAccess/ModularMonolithDDD.Modules.UserAccess.IntegrationEvents/ModularMonolithDDD.Modules.UserAccess.IntegrationEvents.csproj
RUN dotnet restore mmdddshop-backend/src/API/ModularMonolithDDD.API/ModularMonolithDDD.API.csproj

# Copy source code for build
COPY mmdddshop-backend/src/API ./mmdddshop-backend/src/API
COPY mmdddshop-backend/src/BuildingBlocks ./mmdddshop-backend/src/BuildingBlocks
COPY mmdddshop-backend/src/Modules ./mmdddshop-backend/src/Modules

# PUBLISH STAGE
# Publishes to /app/publish
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR /
RUN dotnet publish "mmdddshop-backend/src/API/ModularMonolithDDD.API/ModularMonolithDDD.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# FINAL STAGE
# Copies the published files from /app/publish and runs
# Final image to run
FROM runtime AS final
WORKDIR $APP_HOME
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ModularMonolithDDD.API.dll"]