# ===== Stage 1: Build app =====
FROM node:20 AS builder

WORKDIR /app

# Cài đặt dependencies
COPY package*.json ./
RUN npm install

# Copy all source code and build the project
COPY . .
ARG VITE_API_URL
ARG VITE_AUTHORITY
ARG VITE_CLIENT_ID
ARG VITE_REDIRECT_URI
ENV VITE_API_URL=$VITE_API_URL \
    VITE_AUTHORITY=$VITE_AUTHORITY \
    VITE_CLIENT_ID=$VITE_CLIENT_ID \
    VITE_REDIRECT_URI=$VITE_REDIRECT_URI
RUN npm run build


# ===== Stage 2: Serve with NGINX =====
# FROM nginx:stable-alpine AS dev
FROM nginx:stable AS dev

# Install netcat for wait-for-api-dev script running
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Copy the build output from stage 1 to the Nginx directory for serving
COPY --from=builder /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the custom Nginx configuration if available
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy script wait-for-api
COPY wait-for-api-dev.sh /wait-for-api-dev.sh
RUN chmod +x /wait-for-api-dev.sh

# Expose port (HTTP)
EXPOSE 80

# Start NGINX
ENV API_HOST_PORT=$API_HOST_PORT

ENTRYPOINT ["/wait-for-api-dev.sh"]
CMD ["nginx", "-g", "daemon off;"]

## JSON Array form
# ENTRYPOINT ["/wait-for-api-dev.sh", "api", "5000"]
# CMD ["npm", "run", "dev", "--", "--port", "3000", "--host", "0.0.0.0"]